# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('sfid', models.CharField(db_column='Id', max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('global_region_c', models.CharField(blank=True, max_length=80, null=True)),
                ('global_subregion_c', models.CharField(blank=True, max_length=80, null=True)),
                ('systemmodstamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('sfid', models.CharField(db_column='Id', max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('systemmodstamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sfid', models.CharField(db_column='Id', max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True)),
                ('systemmodstamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='ForceAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('user_token', models.CharField(max_length=80)),
                ('consumer_key', models.CharField(max_length=120)),
                ('consumer_secret', models.CharField(max_length=120)),
                ('request_token_url', models.CharField(default='https://login.salesforce.com/services/oauth2/token', max_length=255)),
                ('access_token_url', models.CharField(default='https://login.salesforce.com/services/oauth2/token', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstalledProduct',
            fields=[
                ('sfid', models.CharField(db_column='Id', max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('product_description_c', models.TextField(blank=True, max_length=4000, null=True)),
                ('systemmodstamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_cred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.ForceAPI')),
            ],
            options={
                'db_table': 'installedproduct',
            },
        ),
        migrations.CreateModel(
            name='ServiceGroupMembers',
            fields=[
                ('sfid', models.CharField(db_column='Id', max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('svmxc_email_c', models.EmailField(blank=True, max_length=80, null=True)),
                ('systemmodstamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_cred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.ForceAPI')),
            ],
            options={
                'db_table': 'servicegroupmembers',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('sfid', models.CharField(db_column='Id', max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('binder_date_acknowledged_c', models.DateField(blank=True, null=True)),
                ('case_spr_number_c', models.TextField(blank=True, max_length=1300, null=True)),
                ('hcls_cor_req_comp_dt_c', models.DateTimeField(blank=True, null=True)),
                ('recordtypeid', models.CharField(blank=True, max_length=18, null=True)),
                ('svmxc_actual_restoration_c', models.DateTimeField(blank=True, null=True)),
                ('svmxc_completed_date_time_c', models.DateTimeField(blank=True, null=True)),
                ('svmxc_country_c', models.CharField(blank=True, max_length=255, null=True)),
                ('svmxc_order_type_c', models.CharField(blank=True, max_length=255, null=True)),
                ('systemmodstamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_cred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.ForceAPI')),
                ('svmxc_case_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.Case')),
                ('svmxc_company_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.Account')),
                ('svmxc_component_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.InstalledProduct')),
                ('svmxc_contact_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.Contact')),
                ('svmxc_group_member_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.ServiceGroupMembers')),
            ],
            options={
                'db_table': 'serviceorder',
            },
        ),
        migrations.CreateModel(
            name='SFUser',
            fields=[
                ('sfid', models.CharField(db_column='Id', max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('sso_c', models.CharField(blank=True, max_length=80, null=True)),
                ('systemmodstamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.SFUser')),
            ],
            options={
                'db_table': 'sfuser',
            },
        ),
        migrations.AddField(
            model_name='servicegroupmembers',
            name='svmxc_salesforce_user_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.SFUser'),
        ),
        migrations.AddField(
            model_name='contact',
            name='api_cred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.ForceAPI'),
        ),
        migrations.AddField(
            model_name='case',
            name='api_cred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.ForceAPI'),
        ),
        migrations.AddField(
            model_name='account',
            name='api_cred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.ForceAPI'),
        ),
    ]
