# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('api_cred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.ForceAPI')),
            ],
        ),
        migrations.CreateModel(
            name='MapField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_api_name', models.CharField(max_length=80)),
                ('sf_label', models.CharField(blank=True, max_length=80, null=True)),
                ('dj_attr', models.CharField(blank=True, max_length=40, null=True)),
                ('db_field', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('=', 'Equals'), ('!=', 'Not equal'), ('<', 'Less Than'), ('<=', 'Less than or equal'), ('>=', 'Greater than or equal'), ('>', 'Greater than'), ('StartsWith', 'Starts With'), ('Contains', 'Contains'), ('EndsWith', 'Ends With'), ('in', 'in'), ('not in', 'not in'), ('includes', 'includes'), ('excludes', 'excludes')], max_length=20)),
                ('value', models.CharField(blank=True, max_length=150, null=True)),
                ('logic', models.CharField(blank=True, choices=[('DELTAxDAYS', 'Offset x Days from now'), ('FLDCMPR', 'Compare to x Field')], max_length=40, null=True)),
                ('logic_param', models.IntegerField(blank=True, null=True)),
                ('map_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.MapField')),
            ],
        ),
        migrations.CreateModel(
            name='MapObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_api_name', models.CharField(max_length=80)),
                ('sf_label', models.CharField(blank=True, max_length=80, null=True)),
                ('dj_class', models.CharField(blank=True, max_length=40, null=True)),
                ('db_table', models.CharField(blank=True, max_length=64, null=True)),
                ('data_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.DataMap')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='api_cred',
        ),
        migrations.RemoveField(
            model_name='case',
            name='api_cred',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='api_cred',
        ),
        migrations.RemoveField(
            model_name='installedproduct',
            name='api_cred',
        ),
        migrations.RemoveField(
            model_name='servicegroupmembers',
            name='api_cred',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='api_cred',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sfid',
            field=models.CharField(db_column='id', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='sfid',
            field=models.CharField(db_column='id', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sfid',
            field=models.CharField(db_column='id', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='installedproduct',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='installedproduct',
            name='sfid',
            field=models.CharField(db_column='id', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicegroupmembers',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='servicegroupmembers',
            name='sfid',
            field=models.CharField(db_column='id', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='sfid',
            field=models.CharField(db_column='id', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sfuser',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='sfuser',
            name='sfid',
            field=models.CharField(db_column='id', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mapfield',
            name='map_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.MapObject'),
        ),
        migrations.AddField(
            model_name='mapfield',
            name='sf_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sf_relation', to='nps.MapObject'),
        ),
    ]
