# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0002_auto_20161021_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegroupmembers',
            name='svmxc_salesforce_user_c',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.SFUser'),
        ),
        migrations.AlterField(
            model_name='sfuser',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.SFUser'),
        ),
    ]
