# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0003_auto_20161024_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='map_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.MapObject'),
        ),
        migrations.AddField(
            model_name='case',
            name='map_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.MapObject'),
        ),
        migrations.AddField(
            model_name='contact',
            name='map_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.MapObject'),
        ),
        migrations.AddField(
            model_name='datamap',
            name='last_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamap',
            name='map_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installedproduct',
            name='map_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.MapObject'),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='last_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='record_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicegroupmembers',
            name='map_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.MapObject'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='map_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.MapObject'),
        ),
        migrations.AddField(
            model_name='sfuser',
            name='map_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.MapObject'),
        ),
    ]
