# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0004_auto_20161025_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('freq_unit', models.CharField(choices=[('HR', 'Hours'), ('DY', 'Days'), ('WK', 'Week'), ('MO', 'Month'), ('YR', 'Year')], max_length=2)),
                ('start', models.DateTimeField(default=datetime.datetime(2016, 10, 25, 19, 53, 8, 675815, tzinfo=utc))),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('next_itr', models.DateTimeField(blank=True, editable=False, null=True)),
                ('data_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.DataMap')),
            ],
        ),
    ]
