# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0005_mapsched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsched',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 25, 19, 56, 38, 455791, tzinfo=utc)),
        ),
    ]
