# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0007_auto_20161025_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsched',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
