# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0008_auto_20161025_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsched',
            name='freq_unit',
            field=models.CharField(choices=[('HR', 'Hours'), ('DY', 'Days'), ('WK', 'Weeks'), ('MO', 'Months'), ('YR', 'Years')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mapsched',
            name='next_itr',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
